name: Laravel CI - Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Install Npm dependencies
        run: npm install

      - name: Compile assets
        run: npm run build

      - name: Run Laravel Pint for code style
        run: ./vendor/bin/pint --test

      - name: Clear config
        run: php artisan config:clear

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/pest
